name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: TooYoungTooSimp/s805-armbian-build@master
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "s805-armbian-build"                        # build=image, kernel=kernel
          armbian_board:     "onecloud"                   # build target
